services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - FAKER_DATABASE_URL=postgres://postgres:dev123@db:5432/api_faker_dev?sslmode=disable
    volumes:
      - ./app:/app
    networks:
      - api_faker_network
    env_file:
      - ./config/.env

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123
    ports:
      - "5432:5432"
    networks:
      - api_faker_network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  api_faker_network:
    driver: bridge

volumes:
  db_data:
